name: os_e2e_schedule

on:
  # refer: https://crontab.guru/examples.html
  # At 00:00 on every saturday（Beijing Time).
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 6'

env:
  VSPHERE_USER: ${{ secrets.VSPHERE_USER }}
  VSPHERE_PASSWD: ${{ secrets.VSPHERE_PASSWD }}
  AMD_ROOT_PASSWORD: ${{ secrets.AMD_ROOT_PASSWORD }}
  KYLIN_VM_PASSWORD: ${{ secrets.KYLIN_VM_PASSWORD }}

jobs:
  build-push-for-e2e:
    uses: ./.github/workflows/build-push-for-e2e.yml

  schedule_os_e2e:
    needs: build-push-for-e2e
    runs-on: [self-hosted, online]
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.4

      - name: os_compitable_e2e_schedule
        run: |
          CONTAINER_TAG="$(git describe --tags --abbrev=8 --dirty)-e2e"
          HELM_CHART_VERSION=`echo ${CONTAINER_TAG}|awk -F "-" '{print $1 }'`
          TAG_SECOND_PART=`echo ${CONTAINER_TAG}|awk  -F "-" '{print $2 }'`
          if [[ ${TAG_SECOND_PART} =~ rc[0-9]+ ]];then 
            HELM_CHART_VERSION=`echo ${CONTAINER_TAG}|awk -F "-" '{print $1"-"$2 }'`
          fi
          echo ${{ runner.name }}
          echo ${{ github.workspace }}
          echo "${HELM_CHART_VERSION}" 
          echo "${CONTAINER_TAG}"
          bash hack/e2e.sh "${HELM_CHART_VERSION}" "${CONTAINER_TAG}" ${{ runner.name }} "${VSPHERE_USER}" "${VSPHERE_PASSWD}" "${AMD_ROOT_PASSWORD}" "${KYLIN_VM_PASSWORD}" "COMPABILITY"